name: Publish VS Code Extension

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm ci
      - run: npm install -g @vscode/vsce

      - run: npm run compile

      - name: Publish Extension
        run: vsce publish    # might need to use: vsce publish -p "$VSCE_PAT"
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
    
